<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Suchi" ignored="0" name="Default test" tests="2" failures="1" timestamp="2022-05-10T15:10:48 IST" time="14.095" errors="0">
  <testcase name="runScenario" time="10.061" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="10.826" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at parallel.Homepagestepdefinition.accounts_section_count_should_be(Homepagestepdefinition.java:58)
at âœ½.accounts section count should be 11(classpath:parallel/Homepage.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
